### ISSUE TITLE
开个 Issues , 假装有人的样子

### ISSUE THREAD

**Issue by medivh-jay** [medivh-jay/starter#4]
六爷爷, 孙悟空到底有几个女朋友啊

**Comment by itstmyi** [comment]
呵呵，假装有问题，心太大了吧？ 给你托一下表示支持。

**Comment by medivh-jay** [comment]
> 呵呵，假装有问题，心太大了吧？ 给你托一下表示支持。
😄😄😄😄

**Comment by medivh-jay** [comment]
> 呵呵，假装有问题，心太大了吧？ 给你托一下表示支持。

那我还是把它关了吧😅😅
